language: node_js
node_js:
    - "0.11"
notifications:
    webhooks:
        urls:
            - http://datisbox.net:7248
        on_success: always
        on_failure: never
        on_start: false

