Vagrant.configure("2") do |config|

   config.vm.provision "docker"

   # The following line terminates all ssh connections. Therefore
   # Vagrant will be forced to reconnect.
   # That's a workaround to have the docker command in the PATH
   config.vm.provision "shell", inline:
     "ps aux | grep 'sshd:' | awk '{print $2}' | xargs kill"

   config.vm.define "ubuntu_dockerhost"
   config.vm.box = "ubuntu/trusty64"
   config.vm.network "forwarded_port",
     guest: 3000, host: 3000

   config.vm.synced_folder "/", "/vagrant", disabled: true

   config.vm.provider :virtualbox do |vb|
     vb.name = "ubuntu_dockerhost"
     vb.memory = 3072
     vb.cpus = 2
   end

end
